###############################################
# Run GitHub's Super Linter against code base #
###############################################
name: GitHub's Super Linter
on: push
jobs:
  run-linters:
    name: GitHub's Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
      - name: Run GitHub Super Linter
        uses: github/super-linter@master
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
[![GitHub's Super Linter](https://github.com/<Nathan-Karafoias>/<ICS3U-Intro-03-Python-Hello_World>/workflows/GitHub's%20Super%20Linter/badge.svg)](https://github.com/<OWNER>/<REPOSITORY>/actions)
